# Generated by Django 5.0.1 on 2026-03-03 17:57

from django.db import migrations, models


def clear_duplicate_phones(apps, schema_editor):
    """Очищаем дубликаты телефонов перед добавлением unique — оставляем первый, остальным ставим NULL."""
    User = apps.get_model('accounts', 'User')
    from django.db.models import Count
    # Находим телефоны, которые встречаются больше одного раза
    duplicates = (
        User.objects.exclude(phone__isnull=True)
        .exclude(phone='')
        .values('phone')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    for row in duplicates:
        phone = row['phone']
        users = User.objects.filter(phone=phone).order_by('id')
        # Оставляем первый, остальным сбрасываем телефон
        for u in users[1:]:
            u.phone = None
            u.save(update_fields=['phone'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_specialty_category_and_fk'),
    ]

    operations = [
        migrations.RunPython(clear_duplicate_phones, noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
