# Generated by Django 5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_phone_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="work_schedule_template",
            field=models.CharField(
                default="standard-5",
                max_length=32,
                verbose_name="Шаблон графика работы",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shift_cycle",
            field=models.CharField(
                blank=True,
                default="2-2",
                max_length=8,
                verbose_name="Цикл смены (для посменного шаблона)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shift_anchor_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата опоры цикла смен",
            ),
        ),
    ]
