# Generated by Django 5.0.1 on 2026-01-20 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('type', models.CharField(choices=[('workday', 'Рабочий день'), ('nonworkday', 'Нерабочий день'), ('sickleave', 'Больничный'), ('vacation', 'Отпуск')], default='workday', max_length=20, verbose_name='Тип дня')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала перерыва')),
                ('end_time', models.TimeField(verbose_name='Время окончания перерыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='bookings.workschedule', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Перерыв',
                'verbose_name_plural': 'Перерывы',
                'ordering': ['start_time'],
            },
        ),
    ]
